using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEditor;

namespace UnityMCP.Editor
{
    /// <summary>
    /// Persistent, queryable project memory and living design intelligence layer.
    /// This is the "long-term brain" for the AI working on this specific Unity project.
    /// It allows the agent to accumulate understanding, record insights from playtests,
    /// maintain a living design document, and make grounded suggestions over time.
    /// </summary>
    public class ProjectMemoryTool : McpToolBase
    {
        public override string ToolName => "project_memory";
        public override string Description => "Persistent project memory, living design doc, and semantic intelligence for this specific game. Enables the AI to remember context, accumulate insights from observations, and develop taste for this project across sessions.";
        public override string Category => "memory";

        private static readonly string MemoryRoot = Path.Combine(Application.dataPath, "Editor/UnityMCP/Memory");
        private const string DesignDocFileName = "living-design-doc.md";
        private const string ProjectModelFileName = "project-model.json";
        private const string InsightsFileName = "insights.jsonl";

        [Serializable]
        public class MemoryParams
        {
            public string action = "status";

            // For record_insight
            public string insightType; // "observation", "design_decision", "gotcha", "performance_note", "vision"
            public string title;
            public string content;
            public string relatedTo; // e.g. "PlayerController", "Jump Mechanics", "Combat"

            // For query
            public string query;
            public int maxResults = 5;

            // For suggest
            public string goal; // e.g. "Make the player jump feel more responsive and snappy"
            public string focusArea; // optional context like "movement" or "combat"

            // For rebuild
            public bool includeScripts = true;
            public bool includeDesignDocs = true;
            public bool scanComments = true;
        }

        public override object Execute(object parameters)
        {
            try
            {
                EnsureMemoryDirectory();

                var args = GetParameters<MemoryParams>(parameters);
                var action = (args.action ?? "status").Trim().ToLowerInvariant();

                return action switch
                {
                    "status" => GetStatus(),
                    "rebuild" => RebuildProjectModel(args),
                    "query" => QueryMemory(args),
                    "record_insight" => RecordInsight(args),
                    "get_design_doc" => GetLivingDesignDoc(),
                    "update_design_doc" => UpdateLivingDesignDoc(args),
                    "suggest" => GenerateSuggestion(args),
                    _ => CreateErrorResponse($"Unknown action '{args.action}'. Supported: status, rebuild, query, record_insight, get_design_doc, update_design_doc, suggest")
                };
            }
            catch (Exception e)
            {
                LogError($"Project memory operation failed: {e.Message}");
                return CreateErrorResponse($"Project memory failed: {e.Message}", e.StackTrace);
            }
        }

        private void EnsureMemoryDirectory()
        {
            if (!Directory.Exists(MemoryRoot))
            {
                Directory.CreateDirectory(MemoryRoot);

                // Create a helpful README so both humans and AI agents understand the system
                var readmePath = Path.Combine(MemoryRoot, "README.md");
                if (!File.Exists(readmePath))
                {
                    var readme = @"# UnityMCP Project Memory

This folder contains the persistent intelligence layer for this Unity project.

## What lives here

- **living-design-doc.md** — The single source of truth for what this game *is*, what it values, and how it should feel. Both humans and the AI should keep this brutally honest and up to date.
- **project-model.json** — Structured index of key systems, design documents, and code intent (generated by `memory.rebuild`).
- **insights.jsonl** — Timestamped learnings recorded from playtests, observations, and design decisions. This is the AI's accumulated wisdom for *this specific game*.

## How to use (for AI agents)

1. Call `memory.status` when starting work on the project.
2. Call `memory.rebuild` to index the current state of the game.
3. Use `memory.query` heavily before making changes.
4. After every `playmode.observe` session, call `memory.recordInsight` with quantitative results and rationale.
5. Use `memory.suggest` when you need grounded advice on a design or tuning problem.
6. Maintain `memory.updateDesignDoc` as the source of truth.

This system is what allows an AI to develop real, compounding understanding of a game over weeks and months instead of treating every session as a cold start.

Do not delete this folder.
";
                    File.WriteAllText(readmePath, readme);
                }

                AssetDatabase.Refresh();
            }
        }

        private object GetStatus()
        {
            var designDocPath = Path.Combine(MemoryRoot, DesignDocFileName);
            var modelPath = Path.Combine(MemoryRoot, ProjectModelFileName);
            var insightsPath = Path.Combine(MemoryRoot, InsightsFileName);

            int insightCount = 0;
            if (File.Exists(insightsPath))
            {
                insightCount = File.ReadAllLines(insightsPath).Length;
            }

            var modelExists = File.Exists(modelPath);
            var docExists = File.Exists(designDocPath);

            string lastRebuild = "Never";
            if (modelExists)
            {
                lastRebuild = File.GetLastWriteTime(modelPath).ToString("yyyy-MM-dd HH:mm");
            }

            return CreateSuccessResponse(new
            {
                memoryPath = MemoryRoot.Replace(Application.dataPath, "Assets"),
                hasLivingDesignDoc = docExists,
                hasProjectModel = modelExists,
                recordedInsights = insightCount,
                lastRebuild = lastRebuild,
                message = "Project memory is active. Use memory.rebuild to index the project and memory.record_insight after important observations."
            }, "Project memory status");
        }

        private object RebuildProjectModel(MemoryParams args)
        {
            var model = new Dictionary<string, object>
            {
                ["lastRebuilt"] = DateTime.UtcNow.ToString("o"),
                ["projectName"] = Application.productName,
                ["unityVersion"] = Application.unityVersion
            };

            var sections = new Dictionary<string, object>();

            if (args.includeDesignDocs)
            {
                sections["designDocuments"] = ScanForDesignDocuments();
            }

            if (args.includeScripts && args.scanComments)
            {
                sections["keySystems"] = ScanScriptsForIntent();
            }

            model["sections"] = sections;

            var modelPath = Path.Combine(MemoryRoot, ProjectModelFileName);
            var json = Newtonsoft.Json.JsonConvert.SerializeObject(model, Newtonsoft.Json.Formatting.Indented);
            File.WriteAllText(modelPath, json);

            AssetDatabase.Refresh();

            return CreateSuccessResponse(new
            {
                modelPath = "Assets/Editor/UnityMCP/Memory/" + ProjectModelFileName,
                sectionsIndexed = sections.Count,
                designDocsFound = sections.ContainsKey("designDocuments") ? ((List<object>)sections["designDocuments"]).Count : 0
            }, "Project model rebuilt successfully");
        }

        private List<object> ScanForDesignDocuments()
        {
            var results = new List<object>();
            var guids = AssetDatabase.FindAssets("t:TextAsset", new[] { "Assets" });

            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var lower = path.ToLowerInvariant();

                if (lower.Contains("design") || lower.Contains("spec") || lower.Contains("readme") || lower.Contains("doc"))
                {
                    try
                    {
                        var content = File.ReadAllText(path);
                        // Store only the first 2000 chars per doc to keep model reasonable size
                        results.Add(new
                        {
                            path = path.Replace(Application.dataPath, "Assets"),
                            preview = content.Length > 2000 ? content.Substring(0, 2000) + "..." : content
                        });
                    }
                    catch { /* ignore unreadable files */ }
                }
            }

            return results;
        }

        private List<object> ScanScriptsForIntent()
        {
            var results = new List<object>();
            var guids = AssetDatabase.FindAssets("t:Script", new[] { "Assets" });

            int scanned = 0;
            foreach (var guid in guids.Take(60)) // Reasonable cap for v1
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                if (path.Contains("/Editor/")) continue;

                try
                {
                    var content = File.ReadAllText(path);
                    var fileName = Path.GetFileNameWithoutExtension(path);

                    // Look for class declaration + summary comments or [DesignIntent] style attributes
                    var hasSummary = content.Contains("/// <summary>") || content.Contains("// Purpose:") || content.Contains("// Intent:");
                    var hasKeyClass = content.Contains("public class " + fileName) || content.Contains("public partial class");

                    if (hasSummary || hasKeyClass)
                    {
                        // Extract a small relevant slice
                        var lines = content.Split('\n');
                        var relevant = string.Join("\n", lines.Take(40));
                        results.Add(new
                        {
                            script = path.Replace(Application.dataPath, "Assets"),
                            snippet = relevant.Length > 1200 ? relevant.Substring(0, 1200) : relevant
                        });
                        scanned++;
                    }
                }
                catch { }
            }

            return results;
        }

        private object QueryMemory(MemoryParams args)
        {
            if (string.IsNullOrWhiteSpace(args.query))
            {
                return CreateErrorResponse("query is required for memory.query");
            }

            var q = args.query.ToLowerInvariant();
            var hits = new List<object>();

            // 1. Search living design doc
            var designDocPath = Path.Combine(MemoryRoot, DesignDocFileName);
            if (File.Exists(designDocPath))
            {
                var doc = File.ReadAllText(designDocPath);
                if (doc.ToLowerInvariant().Contains(q))
                {
                    hits.Add(new
                    {
                        source = "living-design-doc",
                        relevance = "high",
                        content = ExtractRelevantSection(doc, q, 800)
                    });
                }
            }

            // 2. Search project model
            var modelPath = Path.Combine(MemoryRoot, ProjectModelFileName);
            if (File.Exists(modelPath))
            {
                var modelContent = File.ReadAllText(modelPath).ToLowerInvariant();
                if (modelContent.Contains(q))
                {
                    hits.Add(new
                    {
                        source = "project-model",
                        relevance = "medium",
                        content = "Project model contains relevant entries. Consider running memory.rebuild if the index is stale."
                    });
                }
            }

            // 3. Search insights (most valuable for accumulated wisdom)
            var insightsPath = Path.Combine(MemoryRoot, InsightsFileName);
            if (File.Exists(insightsPath))
            {
                var lines = File.ReadAllLines(insightsPath);
                foreach (var line in lines.Reverse().Take(50))
                {
                    if (line.ToLowerInvariant().Contains(q))
                    {
                        hits.Add(new
                        {
                            source = "insights",
                            relevance = "very_high",
                            content = line
                        });
                        if (hits.Count >= args.maxResults) break;
                    }
                }
            }

            if (hits.Count == 0)
            {
                hits.Add(new
                {
                    source = "system",
                    relevance = "low",
                    content = "No strong matches found. The project memory may need a rebuild (memory.rebuild) or more insights recorded from playtests."
                });
            }

            return CreateSuccessResponse(new
            {
                query = args.query,
                resultCount = hits.Count,
                results = hits
            }, $"Memory query completed for: {args.query}");
        }

        private string ExtractRelevantSection(string text, string query, int maxLength)
        {
            var lower = text.ToLowerInvariant();
            var idx = lower.IndexOf(query);
            if (idx < 0) return text.Substring(0, Math.Min(maxLength, text.Length));

            int start = Math.Max(0, idx - 200);
            int end = Math.Min(text.Length, idx + 400);
            var slice = text.Substring(start, end - start);
            if (slice.Length > maxLength) slice = slice.Substring(0, maxLength) + "...";
            return slice;
        }

        private object RecordInsight(MemoryParams args)
        {
            if (string.IsNullOrWhiteSpace(args.content))
            {
                return CreateErrorResponse("content is required when recording an insight");
            }

            var record = new
            {
                timestamp = DateTime.UtcNow.ToString("o"),
                type = args.insightType ?? "general",
                title = args.title ?? "Untitled Insight",
                content = args.content,
                relatedTo = args.relatedTo ?? "General"
            };

            var insightsPath = Path.Combine(MemoryRoot, InsightsFileName);
            var jsonLine = Newtonsoft.Json.JsonConvert.SerializeObject(record) + Environment.NewLine;
            File.AppendAllText(insightsPath, jsonLine);

            return CreateSuccessResponse(new
            {
                recorded = true,
                type = record.type,
                title = record.title,
                totalInsights = File.ReadAllLines(insightsPath).Length
            }, "Insight recorded into project memory");
        }

        private object GetLivingDesignDoc()
        {
            var path = Path.Combine(MemoryRoot, DesignDocFileName);

            if (!File.Exists(path))
            {
                // Create a helpful starter template on first access
                var starter = @"# Living Design Document — " + Application.productName + @"

**This is the single source of truth for this game.** Both humans and AI agents must keep it brutally honest and up to date.

## What This Game Is
- Genre and core fantasy:
- Target player experience / emotion:

## Core Loop
- Primary moment-to-moment gameplay:
- How progression / mastery works:

## Known Good Feel (Quantitative)
- Record real measured values here after successful playtests (e.g. ""Player run speed: 7.2 u/s feels perfect"", ""Jump apex time: 0.38s"")

## Current Tensions & Problems
- 

## Recent Important Decisions + Rationale
- 

## Non-Goals (What We Explicitly Do NOT Want)
- 

---
**Last significant update:** (AI agents: please update this date when making meaningful changes)
**Maintained by:** Humans + UnityMCP Memory Layer
";

                File.WriteAllText(path, starter);
                AssetDatabase.Refresh();
            }

            var content = File.ReadAllText(path);
            return CreateSuccessResponse(new
            {
                path = "Assets/Editor/UnityMCP/Memory/" + DesignDocFileName,
                content = content
            }, "Living design document retrieved");
        }

        private object UpdateLivingDesignDoc(MemoryParams args)
        {
            // For simplicity in v1, we accept full new content via the "content" field when action=update_design_doc
            // In practice the agent will read first, then send back an improved version.
            if (string.IsNullOrWhiteSpace(args.content))
            {
                return CreateErrorResponse("content (full new document) is required for update_design_doc");
            }

            var path = Path.Combine(MemoryRoot, DesignDocFileName);
            File.WriteAllText(path, args.content);
            AssetDatabase.Refresh();

            return CreateSuccessResponse(new
            {
                updated = true,
                path = "Assets/Editor/UnityMCP/Memory/" + DesignDocFileName,
                length = args.content.Length
            }, "Living design document updated");
        }

        /// <summary>
        /// The crown jewel of the memory system. Synthesizes the living design document,
        /// recent recorded insights, and project model to give grounded, context-aware suggestions.
        /// This is what makes the AI feel like it has developed real taste for *this* game.
        /// </summary>
        private object GenerateSuggestion(MemoryParams args)
        {
            if (string.IsNullOrWhiteSpace(args.goal))
            {
                return CreateErrorResponse("goal is required for memory.suggest (e.g. 'Improve the feel of the dash ability')");
            }

            var goal = args.goal;
            var focus = args.focusArea ?? "general";

            // Load all available context
            var designDocPath = Path.Combine(MemoryRoot, DesignDocFileName);
            string designDoc = File.Exists(designDocPath) ? File.ReadAllText(designDocPath) : "No living design document exists yet.";

            var insightsPath = Path.Combine(MemoryRoot, InsightsFileName);
            var recentInsights = new List<string>();
            if (File.Exists(insightsPath))
            {
                recentInsights = File.ReadAllLines(insightsPath)
                    .Reverse()
                    .Take(12)
                    .ToList();
            }

            var modelPath = Path.Combine(MemoryRoot, ProjectModelFileName);
            string modelSummary = File.Exists(modelPath) ? "Project model exists and was last rebuilt recently." : "No project model indexed yet (run memory.rebuild).";

            // Build a rich, structured suggestion payload
            // In a more advanced version this could call an LLM internally. For now we return
            // extremely high-signal structured context that any good agent can reason over.
            var suggestion = new
            {
                goal = goal,
                focusArea = focus,
                synthesizedContext = new
                {
                    livingDesignDocExcerpt = designDoc.Length > 2400 ? designDoc.Substring(0, 2400) + "\n... (truncated)" : designDoc,
                    recentInsights = recentInsights,
                    projectModelStatus = modelSummary
                },
                recommendedApproach = new[]
                {
                    "Review the 'Current Known Good Feel' and 'Recent Decisions' sections of the design doc first.",
                    "Look at quantitative data from previous observations stored in insights.",
                    "Propose changes that respect the core values stated in the Living Design Document.",
                    "After implementing, use playmode.observe + memory.recordInsight to close the learning loop."
                },
                promptForAgent = $"You are an expert designer for this specific game. Goal: {goal}. Use the provided living design document and past insights to propose concrete, measurable next steps. Be specific with numbers and references to existing systems."
            };

            return CreateSuccessResponse(suggestion, $"Suggestion generated for: {goal}");
        }
    }
}